sudo: required
services:
  - docker
before_install:
  - docker build -t ramganesh777/web_app:v1.0 .
script:
  - echo "$password" | docker login -u "$username" --password-stdin
  - docker images
  - docker push ramganesh777/web_app:v1.0
notifications:
  email:
    recipients:
      - ramg.devops@gmail.com
    on_success: always
    on_failure: always
